version: '3.4'

services:
  sagapoc.webapplication:
    image: ${DOCKER_REGISTRY-}sagapocwebapplication
    build:
      context: .
      dockerfile: SagaPoc.WebApplication/Dockerfile
    ports:
      - 8000:80
      - 8800:443
    depends_on:
      - mssql
      - rabbitmq
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1434:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=q1w2e3r4!
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
     - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
     - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
     - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
     RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
     RABBITMQ_DEFAULT_USER: guest
     RABBITMQ_DEFAULT_PASS: guest
    ports:
     - 5672:5672
     - 15672:15672
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
    ports:
      - 9200:9200
  kibana:
    image: kibana:8.3.2
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
